### ISSUE TITLE
Dragonflight bugs

### ISSUE THREAD

**Issue by arcadiatostark** [WoW-MogIt/MogIt#12]
```
4x Interface/AddOns/MogIt/Modules/Extra.lua:1 (null)
4x Interface/AddOns/MogIt/Modules/Base.lua:1 (null)
4x Interface/AddOns/MogIt/Modules/Wishlist.lua:1 (null)
4x Interface/AddOns/MogIt/Core/Tooltip.lua:1 (null)
4x Interface/AddOns/MogIt/Core/GUI.lua:1 (null)
```

Also this is what I see when I type `/mogit` to chat:
![image](https://user-images.githubusercontent.com/116756572/198114680-a62202dd-f45d-4930-89f5-a483f4d6b505.png)

**Comment by VixusFoxy** [comment]
I'm experiencing this exact behavior too. +1

**Comment by Evilvonbek** [comment]
Nil Value issue for most things it tries to do, hopefully something easy to track and sort

I needs me my Mogit :D

**Comment by VixusFoxy** [comment]
It is my understanding that Mogit is no longer actively maintained. If someone is reading this who knows how to fix it, please consider making a pull request.

**Comment by mattfossen** [comment]
One issue I know is that a lot of frames use the SetMaxResize and SetMinResize methods, which were replaced by SetResizeBounds in 10.0. Not sure about the other problems (yet).

**Comment by Silarn** [comment]
I think I've sorted the issues in #13

**Comment by Evilvonbek** [comment]
> I think I've sorted the issues in #13

I'm obviously doing something wrong, but most definitely will be my end.

Deleted Mogit folder, pulled the  zip from your fork and dropped the mogit folder plus subfolders including the module tocs etc into addons folder.

game shows mogit in list, but no datatext/minimap and also no effect for /mogit. not even popping an error anywhere so it's as if I've borked the install somehow? is it meant to be an overwrite and not a clean install?

**Comment by Lombra** [comment]
@Evilvonbek CurseForge does a bunch of magic when packaging addons for download, pulling libraries being the most important one. Installing a raw repository as an addon therefore often will not work. That being said, if you keep the old install (namely, the libraries) and overwrite using the fork, it should work.

**Comment by Evilvonbek** [comment]
@Lombra that's been the issue then. I thought like most "update for compliance" forks it would be better to just nuke the folder and clean install.

I'll grab it again via Curse then do an overwrite and see if that works.

I needs me my Mogit :D

**Comment by Evilvonbek** [comment]
> @Evilvonbek CurseForge does a bunch of magic when packaging addons for download, pulling libraries being the most important one. Installing a raw repository as an addon therefore often will not work. That being said, if you keep the old install (namely, the libraries) and overwrite using the fork, it should work.

tried pulling Mogit from Forge then dropping the repo over it, no joy. looks like I'll just have to wait for the update for DF when it happens
