### ISSUE TITLE
Professions window lua error

### ISSUE THREAD

**Issue by brett1337** [WoW-MogIt/MogIt#16]
Hi,

Super stoked about the DF update, but I did run into one small issue when opening profession window (I'm using ATT also) and when mousing over a reagent (Leystone Ore in Relic of the Past I recipe in this case):

Message: Interface/AddOns/MogIt/Core/Tooltip.lua:270: attempt to call field 'GetRecipeReagentItemLink' (a nil value)
Time: Thu Nov  3 10:59:06 2022
Count: 3
Stack: Interface/AddOns/MogIt/Core/Tooltip.lua:270: attempt to call field 'GetRecipeReagentItemLink' (a nil value)

Locals:

**Comment by Lombra** [comment]
Thanks!
