### ISSUE TITLE
Issue with Auctionator & MogIt

### ISSUE THREAD

**Issue by Gena-76** [WoW-MogIt/MogIt#17]
Hello. When using both addons in the 10.0 patch, MogIt causes an issue with a feature of Auctionator. I did some troubleshooting to determine which addon was making this happen while talking with the developer of Auctionator. They told me to pass this on to you:

"Refer them to https://github.com/WoW-MogIt/MogIt/blob/b83f3ba755b24448a8e03618e9d2079556de077f/Core/Preview.lua#L897 and explain that the function has 2 possible parameters, the second being an item location when the item comes from a bag"

Thanks and have a nice day.

**Comment by Lombra** [comment]
Hi,

Would you be able to replace your `Preview.lua` file with the attached one in order to see whether that resolves the issue?

`AddOns\Mogit\Core\Preview.lua`

[Preview.zip](https://github.com/WoW-MogIt/MogIt/files/9943898/Preview.zip)

**Comment by Gena-76** [comment]
Hello! I have taken that step and happily, it did resolve the issue. :)

Nice work! Thanks for your help.

**Comment by Lombra** [comment]
Great!
