### ISSUE TITLE
Wishlist "profiles"

### ISSUE THREAD

**Issue by Chloe-Necri** [WoW-MogIt/MogIt#18]
on the old blizzard interface, you could go into "Options -> Interface -> Addons (tab) -> Mogit -> and change settings like to swap "mogit profiles" to another one, which is no longer showing Mogit in the Interface -> addons tab, so i cant change Mogit profiles around on a character.

differ profiles have a separate wishlist of mogs saved to it.

any chance to fix? x <3

**Comment by Lombra** [comment]
Certainly! Didn't notice this, but I see what's going on. In the meantime, you should be able to access the options via the button in the main MogIt frame.
