### ISSUE TITLE
LUA Issues with 9.2.5

### ISSUE THREAD

**Issue by Wyr3d** [WoW-MogIt/MogIt#2]
Since the Curse issue thread has been closed, i will repost the LUA problem here:

Message: Usage: local appearances = C_TransmogCollection.GetCategoryAppearances(category, transmogLocation)
Time: Mon Jun  6 08:36:27 2022
Count: 5
Stack: Usage: local appearances = C_TransmogCollection.GetCategoryAppearances(category, transmogLocation)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetCategoryAppearances'
[string "@Interface\AddOns\MogIt\Core\Core.lua"]:513: in function `?'
[string "@Interface\AddOns\MogIt\Core\Core.lua"]:312: in function <Interface\AddOns\MogIt\Core\Core.lua:311>

Here's hoping this helps it get fixed :P

**Comment by chasaya** [comment]
Just a quick feedback, I've replaced Mogit Core.lua with the one in [KenanY](https://github.com/KenanY)'s pull request above (https://github.com/WoW-MogIt/MogIt/pull/3) and this is indeed working for me, no MogIt related errors occurring anymore. Thanks a ton for providing this fix, hope this can be merged into a release soon!
