### ISSUE TITLE
Tooltip model preview stutters during mouseover of reward item in a quest panel

### ISSUE THREAD

**Issue by ryankhart** [WoW-MogIt/MogIt#22]
I have also tested and confirmed that this bug exists even when all other addons are disabled.

![Animation](https://user-images.githubusercontent.com/3673962/204214260-b65c5e83-24ee-44bc-a916-f356324ed45c.gif)

**Comment by Lombra** [comment]
This issue has been coming and going. (or maybe just staying, I'm not sure) I'll see if I can get to the bottom of it.

**Comment by ripsteakface9000** [comment]
Issue is still reproducing for me with MogIt v3.10.0.

**Comment by ahazanov** [comment]
The issue is at https://github.com/WoW-MogIt/MogIt/blob/master/Core/Tooltip.lua#L92.  For some reason the two links being compared are not exactly the same, even though they are for the same item ID / name.  Extracting the item IDs and comparing those gets rid of the stutter.

**Comment by Faulkal** [comment]
this is the answer! thank you so much for this!
