### ISSUE TITLE
"Owned" Tooltip shows wrong value

### ISSUE THREAD

**Issue by fubaWoW** [WoW-MogIt/MogIt#23]
hi there,
![image](https://user-images.githubusercontent.com/41425685/204342533-a0189e1b-b723-48e6-a7bd-c5ecfedf2b70.png)

this screen was made with my DK so he actually can Transmog it but does not know it.
or maybe.... i did miss something there? :D

**Comment by Lombra** [comment]
Could it be that you have collected the appearance from a different item?

**Comment by fubaWoW** [comment]
yes it is possible, i m gonna check it later
