### ISSUE TITLE
Outfit Preview Model

### ISSUE THREAD

**Issue by Domilana** [WoW-MogIt/MogIt#26]
When I open a Preview, it opens as my character, a Night Elf, right? But then when I try to change the race.. It tries to put the Night Elf skin on the geometry/model of the other race, and it happens with every single race. I tried to reinstall the addon via curseforge to no avail

**Comment by Lombra** [comment]
Hi,

This is "working as intended", I'm afraid. This is something Blizzard would need to fix (as far as I know, at least), and I've been considering just removing the feature because of it.
