### ISSUE TITLE
Unable to interact with tabs on the menu

### ISSUE THREAD

**Issue by Hyvem1nd** [WoW-MogIt/MogIt#28]
Hello!

So I am having an issue where when I try to click on the 'modules' tab or anything else within that screen where no drop downs will pop up. It is preventing me from looking at any appearance catalogues as a result. Is there a known fix for this?

**Comment by Hyvem1nd** [comment]
Message: Interface/SharedXML/UIDropDownMenu.lua:91: calling 'GetWindow' on bad self (Usage: local window = self:GetWindow())
Time: Thu Nov  9 21:04:04 2023
Count: 2
Stack: Interface/SharedXML/UIDropDownMenu.lua:91: calling 'GetWindow' on bad self (Usage: local window = self:GetWindow())
[string "=[C]"]: ?
[string "=[C]"]: in function `GetWindow'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:91: in function `UIDropDownMenu_Initialize'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1167: in function <Interface/SharedXML/UIDropDownMenu.lua:1024>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@Interface/AddOns/MogIt/Libs/Libra/Dropdown.lua"]:80: in function `ToggleMenu'
[string "@Interface/AddOns/MogIt/Core/GUI.lua"]:563: in function <Interface/AddOns/MogIt/Core/GUI.lua:557>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by asamblersz** [comment]
Hi, where I have to write or copy this?

**Comment by asamblersz** [comment]
ok soo how can we fix this problem?

**Comment by Lombra** [comment]
Hi, a new version 3.10.1 is out that should fix this.

**Comment by Ketrel** [comment]
BTW this is what change in the Wow UI code

I did this `git diff -U0 10.1.7 10.2.0 -- UIDropDownMenu.lua `

This is the output
```diff
diff --git a/Interface/SharedXML/UIDropDownMenu.lua b/Interface/SharedXML/UIDropDownMenu.lua
index a715d766..53b42afb 100644
--- a/Interface/SharedXML/UIDropDownMenu.lua
+++ b/Interface/SharedXML/UIDropDownMenu.lua
@@ -90,0 +91 @@ function UIDropDownMenu_Initialize(frame, initFunction, displayMode, level, menu
+       dropDownList:SetWindow(frame:GetWindow());
```
