### ISSUE TITLE
MogIt breaks the functionality of copying a character's outfit to clipboard

### ISSUE THREAD

**Issue by ahazanov** [WoW-MogIt/MogIt#31]
1. Target a player character
2. Right-click the character's portrait and click "Inspect"
3. Click "View in Dressing Room"
4. Click "Link Outfit" and click "Copy to Clipboard (to share online)"

If Swatter is not installed, a dialog comes up saying MogIt was prohibited from calling a protected function.
If Swatter is installed, this error message comes up (and nothing gets copied):

```
Date: 2024-01-14 20:57:39
ID: 1
Error occured in: AddOn: MogIt
Count: 1
Message: Error: AddOn MogIt attempted to call a forbidden function (CopyToClipboard()) from a tainted execution path.
Debug:
   [string "=[C]"]: CopyToClipboard()
   [string "@Interface/SharedXML/DressUpModelFrameMixin.lua"]:58: func()
   [string "@Interface/SharedXML/UIDropDownMenu.lua"]:1009: UIDropDownMenuButton_OnClick()
   [string "*UIDropDownMenuTemplates.xml:131_OnClick"]:1:
      [string "*UIDropDownMenuTemplates.xml:131_OnClick"]:1
Locals:
slashCommand = "/outfit v1 8834,89669,0,110879,110872,2633,25723,110878,110874,8837,110875,110873,77238,-1,0,0,0"
itemTransmogInfoList = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
}

AddOns:
  Swatter, v<%version%> (<%codename%>)
  MogIt, vv3.10.1
  MogItArtifact, vv3.10.1
  MogItOneHanded, vv3.10.1
  MogItOther, vv3.10.1
  MogItPlate, vv3.10.1
  MogItRanged, vv3.10.1
  MogItTwoHanded, vv3.10.1
  BlizRuntimeLib_enUS v10.2.0.100200 <none>
  (ck=fb)
```

**Comment by Lombra** [comment]
I think I have a fix for the exact reproduction steps you provided, but the same issue occurs when Ctrl-clicking items to preview them. I don't have a solution for the latter right now.

This seems to be caused by tainting `HandleModifiedItemClick` and `ItemRefTooltip.SetHyperlink`, which is required for Ctrl-Right click to open in MogIt preview to work. This in turns taints the dressing room frame and so the link menu.

**Comment by Lombra** [comment]
I have a solution that will work until the first time you Ctrl-right click the button to use MogIt preview. That's the best I can do.
