### ISSUE TITLE
Feature Request: Only dress model if modifier pressed

### ISSUE THREAD

**Issue by ryankhart** [WoW-MogIt/MogIt#32]
![image](https://github.com/WoW-MogIt/MogIt/assets/3673962/074efc4a-7a75-4f55-8f9c-1361de0735df)

So, I just got this idea because I both like to see what a piece of gear would look like on current transmog, but I also want the ability to easily not confuse the current item's look with anything else I'm currently wearing. Using a modifier key seems like a great way to do this.

The edited screenshot above is my mockup of the idea.

**Comment by Lombra** [comment]
I was able to add this quickly, though it won't redress the model if you press or release the modifier while the tooltip is visible.

**Comment by ryankhart** [comment]
Ooo nice! Much appreciated. I'm gonna study that commit to see if I can learn a little more about WoW addon development and this addon in particular. Also, looking forward to jumping back into the game to check out this change.
