### ISSUE TITLE
MoP remix crashing

### ISSUE THREAD

**Issue by Velphae** [WoW-MogIt/MogIt#34]
Mogit causes MoP remix to stop responding.

**Comment by 2nukes** [comment]
Getting this too.

**Comment by Okimo** [comment]
Bump
Was working previously fine but now it crashes.
Also when enabled inside game via Addon Control Panel it loads fine.

**Comment by Nelmarai** [comment]
Bump
It worked fine at the start, but a few hours into day 1 the crashes started. Only way to fix it was to disable the addon for myself.

**Comment by xathian** [comment]
There seems to be a huge transmog addon issue with Remix, I don't even have MogIt, I whittled it down to being SetCollector

**Comment by Lombra** [comment]
Tried remix yesterday for a little while, but did not notice any immediate issues. Are you guys doing anything in particular when it occurs? What is the exact nature of the crash? 

There should be a crash log somewhere in the game folder. I don't remember exactly where, right now. If you could upload that after a crash, that might help.

**Comment by station384** [comment]
I am also receiving this error.  It seems to occur on first load,  when loading a Remix char and it checks for new additions.  It is acting like it is stuck in a while loop and in that while loop it is populating a table with values but it never meets the condition too exit the loop so the end result is WOW locks up on load,  and continues to consume memory. 
The odd thing is if you activate the addon after logging in,  this does not seem to occur.    (does it do the recheck only on login event and not a reload event?)

**Comment by Okimo** [comment]
Made a video:
https://youtu.be/6BYgh23mWWk
1) Login without mod
2) Enabling mod inside game
3) Relog with mod (after this point it used to crash)
4) Start a game with mod On and logging in
5) Freeze (Crash)
6) Login without mod (works fine again)
Ps: Going to add time stamps later on

**Comment by link064** [comment]
Possibly similar (and similar fix) to this issue: https://github.com/SLOKnightfall/BetterWardrobe/issues/434

**Comment by Shauren** [comment]
I've been using https://github.com/Shauren/MogIt/commit/36c32331f8cf753e4ed29a3d83863de9a4c6b6cf myself, feel free to try it out and see if it fixes the issue for you as well

**Comment by Velphae** [comment]
> y it

using 36c3233 for what?

**Comment by Shauren** [comment]
To fix the freeze on login

**Comment by ianhays** [comment]
> I've been using [Shauren@36c3233](https://github.com/Shauren/MogIt/commit/36c32331f8cf753e4ed29a3d83863de9a4c6b6cf) myself, feel free to try it out and see if it fixes the issue for you as well

Confirmed fixed for me as well.

**Comment by Lombra** [comment]
Ok, I have noticed that it freezes for a couple of seconds sometimes a moment after login. With the proposed changes it gets staggered over a few frames.

Can you confirm that previously the game locked up unrecoverably (or for several minutes or similar) and what behaviour do you get with the above fix in place?

**Comment by Shauren** [comment]
For me it was
* Retail - always fine
* Remix, no patch - unrecoverable freeze
* Remix, with patch - fine

**Comment by Br3gGames** [comment]
> I've been using [Shauren@36c3233](https://github.com/Shauren/MogIt/commit/36c32331f8cf753e4ed29a3d83863de9a4c6b6cf) myself, feel free to try it out and see if it fixes the issue for you as well

This also fixed my "unrecoverable freeze" issue when loading into MoP Remix (was working find up until I logged in at Shrine of Two Moons, but probably just a coincidence).
