### ISSUE TITLE
Modules show every armor type

### ISSUE THREAD

**Issue by SmokeyDev** [WoW-MogIt/MogIt#37]
It seems that on the version updated for 11.0 despite choosing a module, every armor type is being displayed.
E.g. even if I chose Cloth module, I can see plates, leathers etc.

**Comment by unsigned-ru** [comment]
Also having this issue ^6

**Comment by JediJesseS** [comment]
This was happening before with certain categories e.g. chest pieces and shirts getting mixed together, but now it seems to have spread to different armor types.

**Comment by forfoxsakemary** [comment]
I also have the same problem!

**Comment by Maximos7** [comment]
It is still happening even after the update! Also wishlist doesnt work for me :/

**Comment by m13ax92** [comment]
yes, problem still exists.

**Comment by Lombra** [comment]
I am aware of this issue. I don't have a fix right now.

**Comment by Ketrel** [comment]
To help those hunting, for those unfamiliar with the code, what function queries for the list of items to generate the DB?

**Comment by aus10code** [comment]
> I am aware of this issue. I don't have a fix right now.

This single issue is killing this addons usefulness.  Maybe the devs/contributors could do a write up of what they do and don't know and others can try to help figure it out. I took a look at the code to figure out what's going on but I'm not sure exactly what's going on. Filters have nothing to do with armor type and this is purely a module load issue. This even happens if I don't have other armor types loaded which is bizarre.

**Comment by Ketrel** [comment]
I mostly agree.  I think it's either in the module load code, or in the code that populates the database.

(That other modules can load when the "addons" are disabled is not surprising.  They're just TOC files with no code behind them.  The main addon code looks which are enabled and works accordingly.  Enabling them doesn't actually load something)

**Comment by Lombra** [comment]
It's to do with the fact that you can now view transmogs for all classes. If you don't set the appropriate filters you will get results from all classes, apparently. The second problem now is that people will have those items stored in their databases, which is not trivial to undo.

I had a look earlier and am working on some changes. There is no need to store all items anymore, for one.

**Comment by Maximos7** [comment]
Does this issue messes up the wishlist module? 

I have stored more than 300 sets in there and it doesnt load. I click on it and nothing appears. The sets are there cause i can see them with Betterwardrobe addon but they are not loading properly. I hope ew get a fix on this cause i really cant create without mogit :(

**Comment by Lombra** [comment]
> Does this issue messes up the wishlist module?

It does not. Are you using the latest version? An issue with the wishlist was fixed recently. If that does not help, please enable Lua errors and open a new issue.

**Comment by Maximos7** [comment]
![WoWScrnShot_090924_185545](https://github.com/user-attachments/assets/b2c37766-5192-4928-a5a3-c6f2643e2858)
I dont know if u can see this SS or i need to make it on a site or smtg but here we see my whole list (wishlist) on Load tab in preview. I can load any of my sets to see it but the wishlist doesnt preview anything.

**Comment by Lombra** [comment]
Yes, I understand. Please refer to my previous comment.
