### ISSUE TITLE
Update for TWW?

### ISSUE THREAD

**Issue by Maximos7** [WoW-MogIt/MogIt#38]
Hi. Any chance we get this addon up to date for the upcoming expansion? Thank you!

**Comment by Lombra** [comment]
Hi,

The update is available here, but I must have forgotten to set up the CurseForge integration. Currently awaiting approval.

**Comment by Maximos7** [comment]
Ty man i noticed it now ! Pitty i lost all my sets cause i overwrite the wishlist OMG! I forgot to save it like i do every now and then. I m soooooo saddddd. 300+ sets man!

**Comment by Maximos7** [comment]
Hm i might havent lost them. Wishlist module doesnt work. I click it and nothing appears. I tried with all addons disabled ofc and saved a new set in this list to test it, didnt work.
