### ISSUE TITLE
Character freezes entirely and RAM usage keeps ticking up 

### ISSUE THREAD

**Issue by ItsLyanna** [WoW-MogIt/MogIt#39]
I've had an issue that has persisted for a little bit, where on only one specific character, logging in results in a framerate chug that results in a complete freeze, and what looks to be a memory leak when I look in Task Manager. I'm connecting this to MogIt because through process of elimination I was able to fix the issue by disabling MogIt. It is also similar to the MoP Remix freezing issue that has been reported by others, but this was never a Remix character.

**Comment by Lombra** [comment]
I don't know why this seemed to happen only in Remix, and I don't know why it would happen to you, but this should be a non issue in the upcoming release.
