### ISSUE TITLE
No items showing

### ISSUE THREAD

**Issue by SassyBeard** [WoW-MogIt/MogIt#43]
Hey I don't know what happened, I started using this addon today and on one character it worked great but I switched to an alt after putting one item on my wishlist and now there's nothing showing. I don't know if this is a hidden option that I'm too blind to find or if I broke something. I tried going back to an earlier version of the addon but that is also messed up. (all armor types are shown no matter what you choose). 

I've reinstalled and deleted all the settings/cache multiple times. Nothing seems to work.

![image](https://github.com/user-attachments/assets/35083d10-2b38-4414-a8a8-97ab6c7fd05b)

**Comment by Lombra** [comment]
Hi,

No, that is not right. Please enable Lua errors and then reload/relog to see if you get any errors. (either immediately on login or when trying to browse items)

```
/console scriptErrors 1
```

**Comment by SassyBeard** [comment]
> Hi,
> 
> No, that is not right. Please enable Lua errors and then reload/relog to see if you get any errors. (either immediately on login or when trying to browse items)
> 
> ```
> /console scriptErrors 1
> ```

Hey I seem to have fixed it. For some reason the addon "Postal" was breaking it. But I disabled that addon and now MogIt works perfectly fine.

**Comment by Lombra** [comment]
Great! That is strange, but glad you got it sorted out.
