### ISSUE TITLE
Cannot preview, import, or save all BFA and SL Elite PVP sets

### ISSUE THREAD

**Issue by rcbiddle** [WoW-MogIt/MogIt#6]
A list of bonus IDs has been found for all of these sets except the BFA season 2 ones.  Happy to assist and offer more details as needed.

**Comment by Lombra** [comment]
Hi,

Could you clarify which items you are having issues with? And what is preventing you from previewing them?

**Comment by rcbiddle** [comment]
Yes @Lombra 

The items I am having trouble with are all the Elite PVP transmog set pieces from BFA seasons 1 (Dread Gladiator), 2 (Sinister Gladiator), 3 (Notorious Gladiator), 4 (Corrupted Gladiator), and Shadowlands seasons 1 (Sinful Gladiator), 2 (Unchained Gladiator), 3 (Cosmic Gladiator), and 4 (Eternal Gladiator).  For me, none of the elite appearances appear in their respective armor type catalogues except for SL seasons 3 and 4.  To fix this, I have manually edited my SavedVariables for MogIt to include all of these appearances.  That said, if I right-click these items to open a preview window, the regular gladiator transmog shows instead of the elite.  If I try to import any of the elite pieces from WoWHead or by inputting the bonus ID, the same thing happens.  I don't know why this happens, but it does.

**Comment by Lombra** [comment]
I understand. If you link one of these items into chat, and then Ctrl-Left click it to preview it in the default UI, does it show the correct item? If not, there probably isn't anything I can do about it. That's an issue that occurs with handful of items. If yes, I would have to investigate further.

**Comment by rcbiddle** [comment]
It works in the default UI.  I am happy to help investigate further.  I was actually able to create the plate elite set from Shadowlands season 1 by putting the appearance IDs and modified appearance IDs into SavedVariables.  Part of the reason I think it worked is because the regular S1 items didnt show in the catalogue.

**Comment by Lombra** [comment]
Did you try to reproduce the issue by following exactly the instructions outlined in my previous comment?

**Comment by rcbiddle** [comment]
Yes

**Comment by rcbiddle** [comment]
Yes and no.  If I link the item directly from MogIt, it does not always work.  However, if I have an elite set saved with item pieces not listed in the catalogue, I can still link it in chat and get the correct appearance.  Typically though, it doesnt work.  However, I have found ways of linking these items using other addons and getting the elite appearances in the dressing room.

**Comment by rcbiddle** [comment]
@Lombra I have found a solution!  All I did was update the bonus ID list in the addon's core.  From there, I was able to import essentially anything.  If you would like, I could send you what I've done for a future update.

**Comment by Lombra** [comment]
Great! Ah, bonus IDs... I had almost forgotten about those.

Would love to see your findings.

**Comment by rcbiddle** [comment]
I added my findings as a separate pull request.  Happy to help keep the list updated as more IDs are introduced.
