### ISSUE TITLE
Can't preview anything, can't open achievements

### ISSUE THREAD

**Issue by Crzyw** [WoW-MogIt/MogIt#7]
I'm usually doing tmog runs, where people always link stuff in chat for rolls. This is a massive issue because I can't click it and view if its my armor or if I have it already, nothing works even if the app is up to date, Idk if anyone else experiences this but I truly love this addon but this one issue makes me want to not have it at all. The UI's dont open, I just tried to click on the vault on the map of oribos and that wont even open.

**Comment by Lombra** [comment]
Hello,

Can you clarify the issue, please? Is it chat links that won't work? What are you doing, what are you expecting will happen, and what does happen?

**Comment by Crzyw** [comment]
Hello! so ill try explain best I can, Sometimes when I’m running tmog raids people will link stuff in the chat to put down for roll. It sometimes won’t let me click the items or preview them. So I’m unable to see if they’re leather, cloth, mail, or plate so I have to ask the members “Is it Leather?” then roll when I dont know really what I’m rolling for. 

Another time this happens is when I’m in combat sometimes ill get carried away and want to view someone’s appearance or clothing item or something someone picked up. Ill shift left click it to view it and it won’t open due to the addon. It’s these two bugs that can interfere with the gameplay but i’m unsure how to fix them. I hope this helps and makes sense

**Comment by Lombra** [comment]
So regular item tooltips won't even work, is that it?

I don't quite understand the second issue. What is it you're clicking, exactly?

How do you determine that these issues are due to MogIt? And do you get some error messages? Please make sure to enable error messages using `/console scriptErrors 1` and get back to me with any errors.
