### ISSUE TITLE
Can't preview mog in chat.

### ISSUE THREAD

**Issue by covenelf** [WoW-MogIt/MogIt#9]
MogIt worked great with ElvUI, recently I decided to delete ElvUI and ever since the tooltip doesn't work when hovering on items in chat only. Works everywhere else. Is there any suggestions? Thank you ^^

**Comment by Lombra** [comment]
Hi,

Obviously, the public build is broken for now, but I don't have any issues in the fixed build, and I would think it should've worked before 10.0. Let me know if you're still having issues when the update goes out, hopefully today or tomorrow.
